import ARC_Boundary from "../../data/ARC_Boundary.json";
import ARC_Roads from "../../data/ARC_Roads.json";
import ARC_Sections from "../../data/ARC_Sections.json";
import {
  createBasemapSpec,
  createOptimizationArtifactSpec,
  createOverlaySourceSpec,
} from "../map/engine/contracts";
import { BOUNDARY_BBOX, LOCATION_BUFFER_BOUNDARY } from "../map/generatedBounds";
import {
  FAB_BIOGRAPHY_IMAGE_HINT,
  FAB_NO_IMAGE_URL,
  buildFabPopupRows,
  resolveFabBiographyLink,
  resolveFabRecordImageUrl,
} from "./presentation";
import { FAB_TOUR_DEFINITIONS, FAB_TOUR_STYLES, enrichFabTourRecord } from "./tours";

const buildCoreDataModule = (definition) => ({
  group: "Core data",
  kind: "source",
  ...definition,
});

const CORE_DATA_MODULES = [
  buildCoreDataModule({
    id: "burials",
    label: "Burials",
    description: "Primary asset source data used to generate search and map records.",
    fileName: "Geo_Burials.json",
    sourcePath: "src/data/Geo_Burials.json",
    load: () => import("../../data/Geo_Burials.json"),
  }),
  buildCoreDataModule({
    id: "sections",
    label: "Sections",
    description: "Section polygons and metadata used for map browsing.",
    fileName: "ARC_Sections.json",
    sourcePath: "src/data/ARC_Sections.json",
    load: () => import("../../data/ARC_Sections.json"),
  }),
  buildCoreDataModule({
    id: "roads",
    label: "Roads",
    description: "Road centerlines and overlay geometry used in the map.",
    fileName: "ARC_Roads.json",
    sourcePath: "src/data/ARC_Roads.json",
    load: () => import("../../data/ARC_Roads.json"),
  }),
  buildCoreDataModule({
    id: "boundary",
    label: "Boundary",
    description: "Asset boundary geometry used for bounds and location checks.",
    fileName: "ARC_Boundary.json",
    sourcePath: "src/data/ARC_Boundary.json",
    load: () => import("../../data/ARC_Boundary.json"),
  }),
];

const TOUR_MODULES = FAB_TOUR_DEFINITIONS.map((definition) => ({
  id: `tour:${definition.key}`,
  label: definition.name,
  description: "Boutique tour-stop data used for browsing, popups, and matching.",
  group: "FAB boutique features",
  kind: "tour",
  featureFlag: "fabTours",
  tourKey: definition.key,
  fileName: definition.fileName,
  sourcePath: definition.sourcePath,
  load: definition.load,
}));

const MAP_BASEMAPS = [
  {
    id: "imagery",
    label: "Imagery",
    type: "raster-xyz",
    urlTemplate: "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    minZoom: 0,
    maxZoom: 19,
    tileSize: 256,
  },
  {
    id: "streets",
    label: "Streets",
    type: "raster-xyz",
    urlTemplate: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
    minZoom: 0,
    maxZoom: 19,
    tileSize: 256,
  },
  {
    id: "burials-pmtiles",
    label: "Burials PMTiles",
    type: "pmtiles-vector",
    urlTemplate: "/data/geo_burials.pmtiles",
    rasterFallbackUrlTemplate: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
    minZoom: 10,
    maxZoom: 22,
    tileSize: 256,
  },
].map(createBasemapSpec);

const MAP_OVERLAY_SOURCES = [
  {
    id: "roads",
    label: "Roads",
    type: "geojson",
    format: "geojson",
    sourceModuleId: "roads",
    status: "active",
  },
  {
    id: "boundary",
    label: "Boundary",
    type: "geojson",
    format: "geojson",
    sourceModuleId: "boundary",
    status: "active",
  },
  {
    id: "sections",
    label: "Sections",
    type: "geojson",
    format: "geojson",
    sourceModuleId: "sections",
    status: "active",
  },
  {
    id: "burials-pmtiles",
    label: "Burials PMTiles",
    type: "pmtiles-vector",
    format: "pmtiles-vector",
    publicPath: "/data/geo_burials.pmtiles",
    dataLayer: "burials",
    buildCommand: "bun run build:pmtiles",
    status: "experimental",
  },
].map(createOverlaySourceSpec);

const MAP_OPTIMIZATION_ARTIFACTS = [
  {
    id: "burials-source-geojson",
    label: "Burials GeoJSON source",
    role: "source-of-truth",
    format: "geojson",
    sourceModuleId: "burials",
    filePath: "src/data/Geo_Burials.json",
    buildCommand: "",
    status: "active",
    notes: "Checked-in source data still used as the baseline fallback.",
  },
  {
    id: "burials-source-geoparquet",
    label: "Burials GeoParquet source",
    role: "columnar-canonical",
    format: "geoparquet",
    sourceModuleId: "burials",
    filePath: "src/data/Geo_Burials.parquet",
    buildCommand: "bun run build:geoparquet",
    status: "optional",
    notes: "Preferred build-time source when present; should remain a 1:1 replacement for the GeoJSON record model.",
  },
  {
    id: "burials-search-index",
    label: "Burials search index",
    role: "search-index",
    format: "json",
    sourceModuleId: "burials",
    publicPath: "/data/Search_Burials.json",
    filePath: "public/data/Search_Burials.json",
    buildCommand: "bun run build:data",
    status: "active",
    notes: "Runtime-minified payload consumed by the search and browse UI.",
  },
  {
    id: "burials-pmtiles",
    label: "Burials PMTiles archive",
    role: "delivery-overlay",
    format: "pmtiles-vector",
    sourceModuleId: "burials",
    publicPath: "/data/geo_burials.pmtiles",
    filePath: "public/data/geo_burials.pmtiles",
    buildCommand: "bun run build:pmtiles",
    status: "experimental",
    notes: "Static delivery artifact for the custom engine and PMTiles experiments.",
  },
].map(createOptimizationArtifactSpec);

export const FAB_APP_PROFILE = {
  id: "fab",
  productName: "FAB",
  brand: {
    appName: "Albany Rural Cemetery",
    adminName: "Albany Rural Cemetery Admin",
    mapLoadingTitle: "Albany Rural Cemetery",
    mapLoadingMessage: "Loading map experience…",
    adminLoadingTitle: "Albany Rural Cemetery Admin",
    adminLoadingMessage: "Loading static admin studio…",
  },
  labels: {
    primaryRecordSingular: "burial",
    primaryRecordPlural: "burial records",
    unknownPrimaryRecord: "Unknown burial",
    defaultTourLocationLabel: "Tour location",
    defaultRecordSourceLabel: "Burial record",
  },
  fieldAliases: {
    primaryRecord: {
      objectId: ["OBJECTID", "id"],
      firstName: ["First_Name"],
      lastName: ["Last_Name"],
      fullName: ["Full_Name"],
      section: ["Section"],
      lot: ["Lot"],
      tier: ["Tier"],
      grave: ["Grave"],
      row: ["Row"],
      position: ["Position"],
      birth: ["Birth"],
      death: ["Death"],
      title: ["title", "tourKey"],
      tourKey: ["tourKey", "title"],
      tourName: ["tourName"],
      extraTitle: ["Titles", "extraTitle"],
    },
    boutiqueTourRecord: {
      objectId: ["OBJECTID", "id"],
      firstName: ["First_Name", "First_name"],
      lastName: ["Last_Name"],
      fullName: ["Full_Name"],
      section: ["Section", "ARC_Secton"],
      lot: ["Lot", "ARC_Lot"],
      tier: ["Tier"],
      grave: ["Grave"],
      row: ["Row"],
      position: ["Position"],
      birth: ["Birth"],
      death: ["Death"],
      title: ["title", "Tour_ID"],
      tourKey: ["tourKey", "title", "Tour_ID"],
      tourName: ["tourName", "Tour_Name"],
      extraTitle: ["Titles", "extraTitle"],
    },
  },
  moduleIds: {
    primaryRecord: "burials",
    boundary: "boundary",
    sections: "sections",
    roads: "roads",
  },
  artifacts: {
    searchIndexPublicPath: "/data/Search_Burials.json",
    searchIndexFilePath: "public/data/Search_Burials.json",
    boutiqueMatchesFilePath: "src/data/TourMatches.json",
    generatedConstantsFilePath: "src/features/map/generatedBounds.js",
  },
  map: {
    center: [42.704180, -73.731980],
    zoom: 14,
    roadsData: ARC_Roads,
    boundaryData: ARC_Boundary,
    sectionsData: ARC_Sections,
    defaultViewBounds: [
      [42.694180, -73.741980],
      [42.714180, -73.721980],
    ],
    paddedBoundaryBounds: [
      [BOUNDARY_BBOX[1] - 0.01, BOUNDARY_BBOX[0] - 0.01],
      [BOUNDARY_BBOX[3] + 0.01, BOUNDARY_BBOX[2] + 0.01],
    ],
    locationBufferBoundary: LOCATION_BUFFER_BOUNDARY,
    locationMessages: {
      inactive: "Location inactive",
      active: "Location active",
      locating: "Locating...",
      unsupported: "Geolocation is not supported by your browser",
      unavailable: "Unable to retrieve your location",
      outOfBounds: "You must be within 5 miles of Albany Rural Cemetery",
    },
    pmtilesExperimentStorageKey: "fab:enablePmtilesExperiment",
    defaultBasemapId: "imagery",
    basemaps: MAP_BASEMAPS,
    overlaySources: MAP_OVERLAY_SOURCES,
    storageStrategy: {
      sourceOfTruthFormat: "geojson",
      preferredBuildSourceFormat: "geoparquet",
      preferredDeliveryFormat: "pmtiles-vector",
      preferredSearchFormat: "json",
      migrationGoal: "Treat GeoParquet as a build-time 1:1 replacement for GeoJSON while preserving the existing runtime API and generated artifacts.",
    },
    optimizationArtifacts: MAP_OPTIMIZATION_ARTIFACTS,
  },
  dataModules: [
    ...CORE_DATA_MODULES,
    ...TOUR_MODULES,
  ],
  features: {
    tours: {
      featureFlag: "fabTours",
      label: "Tour",
      definitions: FAB_TOUR_DEFINITIONS,
      styles: FAB_TOUR_STYLES,
      enrichRecord: enrichFabTourRecord,
    },
    boutiqueRecordPresentation: {
      featureFlag: "fabRecordPresentation",
      defaultSourceLabel: "Burial record",
      noImageUrl: FAB_NO_IMAGE_URL,
      biographyImageHint: FAB_BIOGRAPHY_IMAGE_HINT,
      resolveBiographyLink: resolveFabBiographyLink,
      resolveImageUrl: resolveFabRecordImageUrl,
      buildPopupRows: buildFabPopupRows,
    },
  },
};
