import { readFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

import { describe, expect, test } from "bun:test";

import SearchBurials from "../public/data/Search_Burials.json";
import TourBiographyAliases from "../src/data/TourBiographyAliases.json";
import TourMatches from "../src/data/TourMatches.json";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const readRepoFile = (...segments) => (
  readFileSync(path.join(__dirname, "..", ...segments), "utf8")
);

describe("generated artifacts", () => {
  test("marks generated JS constants with a grepable generated comment", () => {
    const generatedBounds = readRepoFile("src/features/map/generatedBounds.js");

    expect(generatedBounds.startsWith("// @generated by scripts/precalculate-metadata.js\n")).toBe(true);
  });

  test("keeps generated JSON artifacts in runtime-compatible strict shapes", () => {
    expect(Array.isArray(SearchBurials)).toBe(true);
    expect(SearchBurials[0]).not.toHaveProperty("__generated__");

    expect(Object.keys(TourBiographyAliases).sort()).toEqual([
      "byName",
      "byNameSectionLot",
      "byPortraitStem",
    ]);
    expect(TourBiographyAliases).not.toHaveProperty("__generated__");

    expect(TourMatches).not.toHaveProperty("__generated__");
    const [firstMatchId, firstMatchRecord] = Object.entries(TourMatches)[0] || [];
    expect(firstMatchId).toMatch(/^burial:/);
    expect(firstMatchRecord).toHaveProperty("source", "tour");
  });
});
