import * as turf from "@turf/turf";

import { APP_PROFILE, getTourModuleDefinitions } from "../features/fab/profile";
import { buildBurialBrowseResult, buildTourBrowseResult } from "../features/browse/browseResults";
import { buildTourLookup, findMatchingTourRecord } from "../features/tours/tourRecordHarmonization";

const PRIMARY_RECORD_MODULE_ID = APP_PROFILE.moduleIds?.primaryRecord || "burials";
const BOUNDARY_MODULE_ID = APP_PROFILE.moduleIds?.boundary || "boundary";
const SEARCH_INDEX_FILE_PATH = APP_PROFILE.artifacts?.searchIndexFilePath || "public/data/Search_Burials.json";
const TOUR_MATCHES_FILE_PATH = APP_PROFILE.artifacts?.tourMatchesFilePath || "src/data/TourMatches.json";
const GENERATED_CONSTANTS_FILE_PATH = APP_PROFILE.artifacts?.generatedConstantsFilePath || "src/features/map/generatedBounds.js";
const PRIMARY_RECORD_LABEL = APP_PROFILE.labels?.primaryRecordSingular || "record";

const cleanValue = (value) => {
  if (value === null || value === undefined) return "";
  return String(value).trim();
};

const buildTourBrowseResults = (serializedModulesById) => {
  const tourDefinitions = getTourModuleDefinitions();
  const records = [];

  tourDefinitions.forEach((definition) => {
    const moduleData = serializedModulesById[definition.id];
    const features = moduleData?.features || [];
    features.forEach((feature) => {
      records.push(buildTourBrowseResult(feature, {
        tourKey: definition.tourKey,
        tourName: definition.label,
      }));
    });
  });

  return records;
};

/**
 * The admin artifact rebuild needs the normalized burial browse result in both
 * the tour-matching pass and the compact search-payload pass. Keeping that
 * shared normalization in one array avoids paying for the same 97k-record
 * transform twice every time an editor regenerates derivatives.
 */
const buildNormalizedBurialEntries = (burialFeatures) => (
  burialFeatures.map((feature) => ({
    feature,
    properties: feature.properties || {},
    burialRecord: buildBurialBrowseResult(feature),
  }))
);

const buildTourMatchesArtifact = (normalizedBurialEntries, serializedModulesById) => {
  const loadedTourRecords = buildTourBrowseResults(serializedModulesById);
  const tourLookup = buildTourLookup(loadedTourRecords);
  const matches = {};

  normalizedBurialEntries.forEach(({ burialRecord }) => {
    const matchedTour = findMatchingTourRecord(burialRecord, tourLookup);

    if (matchedTour) {
      matches[burialRecord.id] = matchedTour;
    }
  });

  return matches;
};

const buildSearchBurialsArtifact = (normalizedBurialEntries, tourMatches) => (
  normalizedBurialEntries.map(({ feature, properties, burialRecord }) => {
    const match = tourMatches[burialRecord.id];

    return {
      i: properties.OBJECTID,
      f: cleanValue(properties.First_Name),
      l: cleanValue(properties.Last_Name),
      s: cleanValue(properties.Section),
      lo: cleanValue(properties.Lot),
      g: cleanValue(properties.Grave),
      t: cleanValue(properties.Tier),
      b: cleanValue(properties.Birth),
      d: cleanValue(properties.Death),
      tk: match ? match.tourKey : "",
      c: feature.geometry?.coordinates || null,
      n: burialRecord.fullNameNormalized,
      sl: burialRecord.searchableLabelLower,
      nv: burialRecord.nameVariantsNormalized,
    };
  })
);

const buildConstantsArtifact = (boundaryFeatureCollection) => {
  const boundaryFeature = boundaryFeatureCollection?.features?.[0] || null;
  if (!boundaryFeature) {
    throw new Error("Boundary feature collection is required to regenerate constants.");
  }

  const boundaryBbox = turf.bbox(boundaryFeature);
  const bufferedBoundary = turf.buffer(boundaryFeature, 8, { units: "kilometers" });

  return `// Auto-generated by the static admin studio
export const BOUNDARY_BBOX = ${JSON.stringify(boundaryBbox)};
export const LOCATION_BUFFER_BOUNDARY = ${JSON.stringify(bufferedBoundary)};
`;
};

export const buildGeneratedArtifacts = (serializedModulesById) => {
  const burialFeatureCollection = serializedModulesById[PRIMARY_RECORD_MODULE_ID];
  const boundaryFeatureCollection = serializedModulesById[BOUNDARY_MODULE_ID];

  if (!burialFeatureCollection?.features) {
    throw new Error(`${PRIMARY_RECORD_LABEL} source data is required to regenerate derived artifacts.`);
  }

  const normalizedBurialEntries = buildNormalizedBurialEntries(burialFeatureCollection.features);
  const tourMatches = buildTourMatchesArtifact(normalizedBurialEntries, serializedModulesById);
  const searchBurials = buildSearchBurialsArtifact(normalizedBurialEntries, tourMatches);
  const constantsSource = buildConstantsArtifact(boundaryFeatureCollection);

  return [
    {
      path: SEARCH_INDEX_FILE_PATH,
      contents: JSON.stringify(searchBurials),
    },
    {
      path: TOUR_MATCHES_FILE_PATH,
      contents: JSON.stringify(tourMatches),
    },
    {
      path: GENERATED_CONSTANTS_FILE_PATH,
      contents: constantsSource,
    },
  ];
};
